import { z } from 'zod';
import {
  AccountType,
  Direction,
  EmotionScore,
  ExecutionSide,
  InstrumentType,
  MarketCondition,
  TradeGrade,
  TradeMistake,
  TradeStatus,
  TradingSession,
} from './enums';

export const AccountSchema = z.object({
  id: z.string().uuid(),
  userId: z.string(),
  name: z.string().min(1).max(80),
  broker: z.string().max(80).nullable(),
  accountType: AccountType,
  currency: z.string().length(3).default('USD'),
  initialBalance: z.number(),
  currentBalance: z.number(),
  color: z.string().nullable(),
  propConfig: z
    .object({
      profitTarget: z.number().positive(),
      maxDailyLoss: z.number().positive(),
      maxDrawdown: z.number().positive(),
      drawdownType: z.enum(['static', 'trailing']),
    })
    .nullable(),
  isActive: z.boolean().default(true),
  createdAt: z.coerce.date(),
  updatedAt: z.coerce.date(),
});
export type Account = z.infer<typeof AccountSchema>;

/** Atomic fill — the raw unit every import normalizes to. */
export const ExecutionSchema = z.object({
  id: z.string().uuid(),
  accountId: z.string(),
  tradeId: z.string().nullable(),
  symbol: z.string().min(1).max(32),
  instrumentType: InstrumentType,
  side: ExecutionSide,
  quantity: z.number().positive(),
  price: z.number().positive(),
  commission: z.number().default(0),
  fees: z.number().default(0),
  swap: z.number().default(0),
  executedAt: z.coerce.date(),
});
export type Execution = z.infer<typeof ExecutionSchema>;

/** Grouped position — what the user thinks of as "a trade". */
export const TradeSchema = z.object({
  id: z.string().uuid(),
  accountId: z.string(),
  userId: z.string(),
  symbol: z.string().min(1).max(32),
  instrumentType: InstrumentType,
  direction: Direction,
  status: TradeStatus,
  openedAt: z.coerce.date(),
  closedAt: z.coerce.date().nullable(),
  qty: z.number().positive(),
  avgEntry: z.number().positive(),
  avgExit: z.number().positive().nullable(),
  initialStop: z.number().positive().nullable(),
  target: z.number().positive().nullable(),
  grossPnl: z.number().nullable(),
  netPnl: z.number().nullable(),
  commissionTotal: z.number().default(0),
  feesTotal: z.number().default(0),
  swapTotal: z.number().default(0),
  pnlPct: z.number().nullable(),
  rRealized: z.number().nullable(),
  rPlanned: z.number().nullable(),
  mae: z.number().nullable(),
  mfe: z.number().nullable(),
  holdSeconds: z.number().int().nonnegative().nullable(),
  strategyId: z.string().nullable(),
  setup: z.string().max(80).nullable(),
  marketCondition: MarketCondition.nullable(),
  session: TradingSession.nullable(),
  timeframe: z.string().max(16).nullable(),
  followedPlan: z.boolean().nullable(),
  mistakes: z.array(TradeMistake).default([]),
  emotionPre: EmotionScore.nullable(),
  emotionDuring: EmotionScore.nullable(),
  emotionPost: EmotionScore.nullable(),
  grade: TradeGrade.nullable(),
  reviewed: z.boolean().default(false),
  tags: z.array(z.string()).default([]),
  notes: z.string().nullable(),
  createdAt: z.coerce.date(),
  updatedAt: z.coerce.date(),
});
export type Trade = z.infer<typeof TradeSchema>;

/** Payload for manual trade creation (web form / mobile FAB) — < 30s entry. */
export const CreateTradeInput = TradeSchema.pick({
  accountId: true,
  symbol: true,
  instrumentType: true,
  direction: true,
  qty: true,
  avgEntry: true,
  avgExit: true,
  initialStop: true,
  target: true,
  openedAt: true,
  closedAt: true,
  commissionTotal: true,
  feesTotal: true,
  swapTotal: true,
  strategyId: true,
  setup: true,
  marketCondition: true,
  session: true,
  timeframe: true,
  followedPlan: true,
  mistakes: true,
  emotionPre: true,
  emotionDuring: true,
  emotionPost: true,
  grade: true,
  tags: true,
  notes: true,
}).partial({
  avgExit: true,
  initialStop: true,
  target: true,
  closedAt: true,
  commissionTotal: true,
  feesTotal: true,
  swapTotal: true,
  strategyId: true,
  setup: true,
  marketCondition: true,
  session: true,
  timeframe: true,
  followedPlan: true,
  mistakes: true,
  emotionPre: true,
  emotionDuring: true,
  emotionPost: true,
  grade: true,
  tags: true,
  notes: true,
});
export type CreateTradeInput = z.infer<typeof CreateTradeInput>;

export const StrategySchema = z.object({
  id: z.string().uuid(),
  userId: z.string(),
  name: z.string().min(1).max(80),
  description: z.string().nullable(),
  instrumentFilter: z.array(InstrumentType).default([]),
  sessionFilter: z.array(TradingSession).default([]),
  timeframe: z.string().max(16).nullable(),
  rrTarget: z.number().positive().nullable(),
  entryRules: z.array(z.string()).default([]),
  exitRules: z.array(z.string()).default([]),
  isActive: z.boolean().default(true),
  createdAt: z.coerce.date(),
});
export type Strategy = z.infer<typeof StrategySchema>;
